Repository FrancescoXX/free-Web3-resources, pull requests merged in 2022-10, with the labels that each got.

#84 [DOCUMENTATION] Add new YT channel in README
  README.md
Labels: hacktoberfest-accepted

#83 Update README.md
  README.md
Labels: hacktoberfest-accepted

#80 Add new section : Open Source Projects
  README.md
Labels: hacktoberfest-accepted

#78 [DOCUMENTATION] Add new YT channel in README
  README.md
Labels: hacktoberfest-accepted

#89 added gitignore file
  .gitignore
Labels: hacktoberfest-accepted

#98 Release dot yaml file added
  .github/workflows/release.yml
Labels: hacktoberfest, hacktoberfest-accepted

#99 Update README.md
  README.md
Labels: hacktoberfest-accepted

#105 Separated Text & Video Roadmaps and added more video roadmaps
  README.md
Labels: hacktoberfest-accepted

#109 Add cryptozombies
  README.md
Labels: hacktoberfest-accepted

#110 Added Vyper Section
  README.md
Labels: hacktoberfest-accepted

#112 Added favicon
  images/favicon_io/favicon.ico
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#111 Yashdev9274 patch 1
  README.md
Labels: hacktoberfest-accepted

#115 Updated readme.md
  README.md
Labels: hacktoberfest-accepted

#120 Added some resources to learn and practice solidity
  README.md
Labels: hacktoberfest

#189 Code snippets
  code-snippets/ERC20Token.sol
  code-snippets/readme.md
Labels: hacktoberfest-accepted

#190 add GitHub icon that redirects to repository
  README.md
Labels: hacktoberfest-accepted

#200 Update README.md
  README.md
Labels: hacktoberfest-accepted

#219 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#231 Removed duplicates under Solana section
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#236 Update README.md
  README.md
Labels: invalid

#239 Added new .yml based issue templates 🛠
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  package-lock.json
  package.json
Labels: hacktoberfest-accepted

#250 add a polygon section
  README.md
Labels: hacktoberfest-accepted
